### ISSUE TITLE
Wrong synthesis result

### ISSUE THREAD

**Issue by Columpio** [victornicolet/atropos#6]
For the following problem
```ocaml
type nat = Z | S of nat

let rec odd = function
  | Z -> false
  | S x -> even x
and even = function
  | Z -> true
  | S x -> odd x

let rec query x = odd x && odd(S (S x))

let rec f x = [%synt fi]

assert (f = query)
```
I get the following result:
```ocaml
let fi  = false

let rec f x = fi
```
which is obviously false as `query(S Z) = true`

**Comment by victornicolet** [comment]
Yes, there is a problem in the way the tool initializes its state when the function to synthesize doesn't decompose its input (by pattern matching).  I will fix this as soon as possible.

In the meantime, you can try rewriting the benchmark as follows:
```[caml]
type nat =
  | Z
  | S of nat

(* Group the functions defining your reference function. *)
let rec query x = odd x && odd (S (S x))

and odd = function
  | Z -> false
  | S x -> even x

and even = function
  | Z -> true
  | S x -> odd x

let rec f x = [%synt fi]
;;
assert (f = query)
```
And use the `-c` option when invoking Synduce (this turns off the optimized initialization that causes the problem). 
Synduce should then answer that there is no solution.
